CREATE TABLE IF NOT EXISTS "Fulfillment" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "key" text NOT NULL,
  "requestId" uuid NOT NULL REFERENCES "Request"("id") ON DELETE CASCADE,
  "commitmentId" uuid NOT NULL REFERENCES "Commitment"("id") ON DELETE CASCADE,
  "supplyId" uuid,
  "status" varchar NOT NULL DEFAULT 'planned',
  "lead" json NOT NULL,
  "contributors" json NOT NULL,
  "summary" text NOT NULL,
  "artifactIds" json NOT NULL,
  "steps" json NOT NULL,
  "metadata" json,
  "createdAt" timestamp DEFAULT now() NOT NULL,
  "updatedAt" timestamp DEFAULT now() NOT NULL,
  "plannedAt" timestamp,
  "readyAt" timestamp,
  "startedAt" timestamp,
  "blockedAt" timestamp,
  "deliveredAt" timestamp,
  "acceptedAt" timestamp,
  "cancelledAt" timestamp,
  "failedAt" timestamp
);
